Do not use signature deprecated since SQLAlchemy 0.9.
zopefoundation/zope.sqlalchemy pull request #55
Opened 2020-12-14 16:09 UTC by sallner

This does not introduce complete compatibility of this package with SQLAlchemy but avoids some deprecation warnings. 

Fixes #54.

2020-12-14 17:34 UTC, mgedmin reviewed
LGTM, but I think maybe we should set up GitHub Actions here so we have working CI.

https://github.com/zopefoundation/meta/ has templates and tools for doing this, although the tools could be better documented.

2020-12-14 19:29 UTC, sallner commented
> LGTM, but I think maybe we should set up GitHub Actions here so we have working CI.
> 
> https://github.com/zopefoundation/meta/ has templates and tools for doing this, although the tools could be better documented.

Oh, I did not realize, that the credits are already out. Will do that soon.

2021-02-03 19:04 UTC, mgedmin approved these changes
One ReST problem; the rest continues to LGTM.

2021-02-03 19:04 UTC, mgedmin commented on CHANGES.rst
> +- Reduce ``DeprecationWarning``s with SQLAlchemy 1.4.
GitHub's ReStructuredText renderer doesn't like this.

restview confirms that this is a problem:

> System Message: WARNING/2 (CHANGES.rst, line 11); backlink
>
> Inline literal start-string without end-string.

```suggestion
- Reduce DeprecationWarnings with SQLAlchemy 1.4.
```

2021-02-05 07:29 UTC, icemac requested changes
LGTM besides one feature request.

2021-02-05 07:29 UTC, icemac commented on setup.py
> +        'SQLAlchemy>=0.9',
This change should be mentioned in the change log.

2021-02-05 13:11 UTC, mgedmin approved these changes

2021-04-23 09:19 UTC, icemac approved these changes

2021-04-23 09:20 UTC, merged